services:
  db:
    image: mysql:latest
    container_name: ${HOST}
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${PASSWORD}
    ports:
      - "${PORT}"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${DB_USER} -p${PASSWORD} || exit 1"]
      timeout: 20s
      retries: 10

  web:
    build: .
    container_name: django-container
    hostname: django-container
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -s http://localhost:8000 || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
      - /tmp:/tmp
    depends_on:
      db:
        condition: service_healthy
      # web:
      #  condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A core beat --loglevel=info
    volumes:
      - .:/app
      - /tmp:/tmp
    depends_on:
      db:
        condition: service_healthy
      # web:
      #  condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env

volumes:
  db_data:
