# Generated by Django 5.2 on 2025-04-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('coordinate', models.JSONField()),
                ('description', models.JSONField()),
                ('display_type', models.CharField(max_length=100)),
                ('extent', models.CharField(max_length=100)),
                ('footer', models.JSONField()),
                ('future', models.BooleanField()),
                ('icon', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255)),
                ('isBlocked', models.CharField(max_length=10)),
                ('lorryParkingFeatureIcons', models.JSONField()),
                ('point', models.CharField(max_length=255)),
                ('routeRecommendation', models.JSONField()),
            ],
        ),
    ]
