# Generated by Django 5.2 on 2025-04-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='coordinate',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='description',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='display_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='extent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='footer',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='future',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='isBlocked',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='lorryParkingFeatureIcons',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='point',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='routeRecommendation',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
