# Generated by Django 5.2 on 2025-04-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_station_coordinate_alter_station_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
