# Generated by Django 5.2 on 2025-04-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_remove_station_coordinate_remove_station_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='road',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
