# Generated by Django 5.2 on 2025-04-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_station_road'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
