# Generated by Django 5.2 on 2025-04-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0010_station_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='title',
        ),
    ]
