# Generated by Django 5.2 on 2025-04-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0011_remove_station_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLorry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(max_length=255)),
                ('is_blocked', models.CharField(max_length=255)),
                ('future', models.BooleanField()),
                ('start_lc_position', models.CharField(blank=True, max_length=255, null=True)),
                ('display_type', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('route_recommendation', models.JSONField(blank=True, default=list, null=True)),
                ('footer', models.JSONField(blank=True, default=list, null=True)),
                ('lorry_parking_feature_icons', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='station',
            old_name='isBlocked',
            new_name='is_blocked',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='lorryParkingFeatureIcons',
            new_name='lorry_parking_feature_icons',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='routeRecommendation',
            new_name='route_recommendation',
        ),
    ]
