# Generated by Django 5.2 on 2025-04-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0012_parkinglorry_rename_isblocked_station_is_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglorry',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parkinglorry',
            name='car_parking_spaces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkinglorry',
            name='lorry_parking_spaces',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
