# Generated by Django 5.2 on 2025-04-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0013_parkinglorry_area_parkinglorry_car_parking_spaces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglorry',
            name='car_parking_spaces',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglorry',
            name='future',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglorry',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglorry',
            name='is_blocked',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglorry',
            name='lorry_parking_spaces',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
