# Generated by Django 5.2 on 2025-04-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0014_alter_parkinglorry_car_parking_spaces_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road', models.CharField(max_length=255)),
                ('isBlocked', models.CharField(max_length=10)),
                ('future', models.BooleanField()),
                ('startLcPosition', models.CharField(max_length=255)),
                ('impact', models.JSONField()),
                ('display_type', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('startTimestamp', models.CharField(max_length=100)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('routeRecommendation', models.JSONField()),
                ('footer', models.JSONField()),
                ('lorryParkingFeatureIcons', models.JSONField()),
                ('geometry', models.JSONField()),
            ],
        ),
    ]
