# Generated by Django 5.2 on 2025-04-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0015_closure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closure',
            name='display_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='footer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='future',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='geometry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='impact',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='isBlocked',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='lorryParkingFeatureIcons',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='road',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='routeRecommendation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='startLcPosition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='startTimestamp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
