# Generated by Django 5.2 on 2025-04-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0016_alter_closure_display_type_alter_closure_footer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closure',
            name='description',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglorry',
            name='description',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='description',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
