# Generated by Django 5.2 on 2025-04-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0017_alter_closure_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road', models.CharField(blank=True, max_length=255, null=True)),
                ('isBlocked', models.CharField(blank=True, max_length=10, null=True)),
                ('future', models.BooleanField(blank=True, null=True)),
                ('startLcPosition', models.CharField(blank=True, max_length=255, null=True)),
                ('impact', models.JSONField(blank=True, null=True)),
                ('display_type', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('startTimestamp', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('routeRecommendation', models.JSONField(blank=True, null=True)),
                ('footer', models.JSONField(blank=True, null=True)),
                ('lorryParkingFeatureIcons', models.JSONField(blank=True, null=True)),
                ('geometry', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='closure',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglorry',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
