from django.db import models

class Station(models.Model):
    road = models.CharField(max_length=255, null=True, blank=True)
    area = models.CharField(max_length=255, null=True, blank=True)
    subtitle = models.CharField(max_length=255, null=True, blank=True)
    latitude = models.CharField(max_length=255, null=True, blank=True)
    longitude = models.CharField(max_length=255, null=True, blank=True)
    description = models.CharField(max_length=2000, null=True, blank=True)
    display_type = models.CharField(max_length=100, null=True, blank=True)
    extent = models.CharField(max_length=100, null=True, blank=True)
    footer = models.JSONField(null=True) 
    future = models.BooleanField(null=True)
    icon = models.CharField(max_length=255, null=True, blank=True)
    is_blocked = models.CharField(max_length=10, null=True, blank=True)
    lorry_parking_feature_icons = models.JSONField(null=True)
    point = models.CharField(max_length=255, null=True, blank=True)
    route_recommendation = models.JSONField(null=True)

class ParkingLorry(models.Model):
    road = models.CharField(max_length=255, null=True, blank=True)
    area = models.CharField(max_length=255, null=True, blank=True)
    car_parking_spaces = models.CharField(max_length=255, null=True, blank=True)
    lorry_parking_spaces = models.CharField(max_length=255, null=True, blank=True)
    icon = models.CharField(max_length=255, null=True, blank=True)
    is_blocked = models.CharField(max_length=255, null=True, blank=True)
    future = models.BooleanField(null=True, blank=True)
    start_lc_position = models.CharField(max_length=255, null=True, blank=True)
    display_type = models.CharField(max_length=255, null=True, blank=True)
    subtitle = models.CharField(max_length=255, null=True, blank=True)
    title = models.CharField(max_length=255, null=True, blank=True)
    latitude = models.CharField(max_length=255, null=True, blank=True)
    longitude = models.CharField(max_length=255, null=True, blank=True)
    description = models.CharField(max_length=2000, null=True, blank=True)
    route_recommendation = models.JSONField(default=list, null=True, blank=True)
    footer = models.JSONField(default=list, null=True, blank=True)
    lorry_parking_feature_icons = models.JSONField(default=list, null=True, blank=True)